name: lcd_data
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pip
  - pipreqs
  - pre-commit
  - ruff
  - mypy
  - mamba
  - geopandas
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - requests
  - shapely
  - xarray
  - jupyter_client
  - jupyter_core
  - notebook
  - ipykernel
  - pip:
      - git+https://github.com/jankazil/lcd-data
